security:
  firewalls:       
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        context: dev
        security: false
        
    secured_area:
        pattern: ^/*
        anonymous: ~
        form_login:
             login_path: /login
             check_path: /autenticar
             post_only:   false
             always_use_default_target_path: true
             default_target_path: /principal          
        logout:
             path: /logout 
             target: /login
             invalidate_session: true
             delete_cookies:
                    name:
                       path: ~
                       domain: ~
  access_control: 
    - { path: ^/login*, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
    - { path: ^/principal*, roles: ROLE_USER }
    - { path: ^/perfil, roles: ROLE_USER }    
    - { path: ^/admin, roles: [ ROLE_ADMIN, ROLE_ENLACE ] }
    - { path: ^/admin/bitacora, roles: ROLE_ADMIN }
    - { path: ^/proyectos*, roles: ROLE_USER }
    - { path: ^/ejecucion*, roles: ROLE_USER }    
          
  providers:        
     base_datos:
         entity: {class: SisproBundle:Usuario}
 
  role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

  encoders:     
     Mcti\SisproBundle\Entity\Usuario:
           algorithm:        sha1
           encode_as_base64: false
           iterations:       1   
