services:
    captcha.type:
        class: Gregwar\CaptchaBundle\Type\CaptchaType
        arguments:
            - @session
            - @gregwar_captcha.generator
            - @translator
            - %gregwar_captcha.config%
        tags:
            - { name: form.type, alias: captcha }

    gregwar_captcha.generator:
        class: Gregwar\CaptchaBundle\Generator\CaptchaGenerator
        arguments:
            - @router
            - @gregwar_captcha.captcha_builder
            - @gregwar_captcha.phrase_builder
            - @gregwar_captcha.image_file_handler

    gregwar_captcha.image_file_handler:
        class: Gregwar\CaptchaBundle\Generator\ImageFileHandler
        arguments:
            - %gregwar_captcha.config.image_folder%
            - %gregwar_captcha.config.web_path%
            - %gregwar_captcha.config.gc_freq%
            - %gregwar_captcha.config.expiration%

    gregwar_captcha.captcha_builder:
        class: Gregwar\Captcha\CaptchaBuilder

    gregwar_captcha.phrase_builder:
        class: Gregwar\Captcha\PhraseBuilder
