Mcti\SisproBundle\Entity\Fotografia:
    type: entity
    table: fotografia
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: SEQUENCE
        imagen:
            type: text
            nullable: false
        comentarios:
            type: text
            nullable: false
    manyToOne:
        actividad:
            targetEntity: Actividad
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                actividad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
