Mcti\SisproBundle\Entity\MetaAlcanzada:
    type: entity
    table: meta_alcanzada
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: SEQUENCE
        meta:
            type: decimal
            nullable: false
        observaciones:
            type: text
            nullable: true
        fecha:
            type: date
            nullable: false
    manyToOne:
        actividad:
            targetEntity: Actividad
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                actividad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
