Mcti\SisproBundle\Entity\Usuario:
    type: entity
    repositoryClass: Mcti\SisproBundle\Entity\UsuarioRepository
    table: usuario
    fields:
        id:
            id: true
            type: smallint
            nullable: false
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 50
            fixed: false
            nullable: false
        apellido:
            type: string
            length: 50
            fixed: false
            nullable: false
        correo:
            type: string
            length: 150
            fixed: false
            nullable: false
        clave:
            type: string
            length: 200
            fixed: false
            nullable: false
        cargo:
            type: string
            length: 50
            fixed: false
            nullable: true
        telefono:
            type: string
            length: 50
            fixed: false
            nullable: true
        usuario:
            type: string
            length: 150
            fixed: false
            nullable: false
        activo:
            type: boolean
            nullable: false
        salt:
            type: string
            length: 200
            fixed: false
            nullable: false
        tiempoBloqueo:
            type: integer
            unsigned: false
            nullable: false
            column: tiempo_bloqueo
        intentos:
            type: smallint
            nullable: false
    manyToMany:
        role:
            targetEntity: Role
            inversedBy: usuario
            joinTable:
                name: usuario_role
                joinColumns:
                    -
                        name: usuario_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: role_id
                        referencedColumnName: id
            orderBy: null
    manyToOne:
        estructura:
            targetEntity: Estructura
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                estructura_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
