<?php

namespace Mcti\SisproBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRepository extends EntityRepository
{
    /*
     * Obtiene un array con los estados
     */
    public function getArrayEstados()
    {
        $estados= $this->getEntityManager()
                       ->createQuery('SELECT e.id, e.estado 
                                      FROM SisproBundle:Estado e                                  
                                      ORDER BY e.estado ASC')
                       ->getResult();
       
        if (count($estados)==0) return array('0'=>'');
            
        $a=array('0'); $b=array('[Seleccione]');
        
        foreach ($estados as $fila)
        {
           array_push($a,$fila['id']);
           array_push($b,$fila['estado']);
        }         
        $estados=array_combine($a,$b);
        //ksort($estados);        
        return $estados;
    }
    
}
