<?php

namespace Mcti\SisproBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParroquiaRepository extends EntityRepository
{
    /*
     * Obtiene un array con las parroquias del municipio dado
     */
    public function getArrayParroquias($idMunicipio)
    {
        $parroquias= $this->getEntityManager()
                       ->createQuery('SELECT p.id, p.parroquia
                                      FROM SisproBundle:Parroquia p
                                      JOIN p.municipio m
                                      WHERE m.id=:id
                                      ORDER BY p.parroquia ASC')
                       ->setParameter('id', $idMunicipio)
                       ->getResult();
       
        if (count($parroquias)==0) return array('0'=>'');
            
        $a=array('0'); $b=array('[Seleccione]');
        
        foreach ($parroquias as $fila)
        {
           array_push($a,$fila['id']);
           array_push($b,$fila['parroquia']);
        }         
        $parroquias=array_combine($a,$b);
        //ksort($estados);        
        return $parroquias;
    }
    
}
