<?php

namespace Mcti\SisproBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PobladoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PobladoRepository extends EntityRepository
{
    /*
     * Obtiene un array con los poblados del municipio dado
     */
    public function getListaPoblados($idMunicipio, $frase)
    {
        $poblados= $this->getEntityManager()
                       ->createQuery("SELECT p.id, p.poblado
                                      FROM SisproBundle:Poblado p
                                      JOIN p.municipio m
                                      WHERE (m.id=:id)
                                      AND (p.poblado LIKE :frase)
                                      ORDER BY p.poblado ASC")
                       ->setParameter('id', $idMunicipio)
                       ->setParameter('frase', "%$frase%")
                       ->getResult();
        return json_encode($poblados);
    }
    
}
