<?php

namespace Mcti\SisproBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroNotificacionRepository extends EntityRepository
{
    /*
     * Obtiene el último registro de notificacion
     */
    public function findUltimaNotificacion()
    {
        $query = $this->getEntityManager()
                    ->createQuery('SELECT r
                                   FROM SisproBundle:RegistroNotificacion r                                  
                                   ORDER BY r.fecha DESC')                    
                    ->setMaxResults(1);
        try {
             $resultado = $query->getSingleResult();
            } catch (\Doctrine\Orm\NoResultException $e) {
              $resultado = false;
            }
        return $resultado;
    }
    
}
